# Generated by Django 3.0.6 on 2020-07-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200719_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to='portfolio/image/')),
                ('img2', models.ImageField(blank=True, upload_to='portfolio/image/')),
                ('img3', models.ImageField(blank=True, upload_to='portfolio/image/')),
                ('img4', models.ImageField(blank=True, upload_to='portfolio/image/')),
                ('img5', models.ImageField(blank=True, upload_to='portfolio/image/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project')),
            ],
        ),
    ]
