# Generated by Django 3.0.6 on 2020-07-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Machine Learning', 'Machine Learning')], default='Web Development', max_length=20),
        ),
    ]
