# Generated by Django 3.0.6 on 2020-07-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
