# Generated by Django 3.0.6 on 2020-07-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200721_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img6',
            field=models.ImageField(blank=True, upload_to='portfolio/image/'),
        ),
        migrations.AddField(
            model_name='image',
            name='img7',
            field=models.ImageField(blank=True, upload_to='portfolio/image/'),
        ),
    ]
