# Generated by Django 3.0.6 on 2020-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200721_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/certificate/')),
                ('issue_date', models.DateField()),
                ('certificate_id', models.CharField(max_length=50)),
            ],
        ),
    ]
