# Generated by Django 3.0.6 on 2020-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
