# Generated by Django 3.0.6 on 2020-07-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img8',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='img1',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='img2',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='img3',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='img4',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='img5',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='img6',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='img7',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
